# --- !Ups
DROP TABLE IF EXISTS folders CASCADE;
CREATE TABLE folders (
  id      SERIAL NOT NULL PRIMARY KEY,
  user_id INT    NOT NULL REFERENCES users ON DELETE CASCADE ON UPDATE RESTRICT,
  name    TEXT   NOT NULL,
  parent  INT REFERENCES folders ON DELETE SET NULL ON UPDATE RESTRICT
);

# --- !Downs
DROP TABLE IF EXISTS folders CASCADE;
