# --- !Ups
-- cascade deletion 
DROP TABLE IF EXISTS folders CASCADE;
CREATE TABLE folders (
  id      SERIAL NOT NULL PRIMARY KEY,
  user_id INT    NOT NULL REFERENCES users ON DELETE CASCADE ON UPDATE RESTRICT,
  name    TEXT   NOT NULL,
  parent  INT REFERENCES folders ON DELETE CASCADE ON UPDATE RESTRICT
);

DROP TABLE IF EXISTS links CASCADE;
CREATE TABLE links (
  id          SERIAL NOT NULL PRIMARY KEY,
  user_id     INT    NOT NULL REFERENCES users ON DELETE CASCADE ON UPDATE RESTRICT,
  url         TEXT   NOT NULL,
  name        TEXT   NOT NULL,
  description TEXT,
  parent      INT REFERENCES folders ON DELETE CASCADE ON UPDATE RESTRICT
);

# --- !Downs
DROP TABLE IF EXISTS folders CASCADE;
DROP TABLE IF EXISTS links CASCADE;
